name: CI

on:
  push: 
  pull_request:
    branches: [ main, dev ]

jobs:
  cypress-tests:

    runs-on: self-hosted
    container: cypress/browsers:node16.14.0-slim-chrome99-ff97

    steps:
    - uses: actions/checkout@v2
    - name: Cypress ct
      uses: cypress-io/github-action@v2
      with:
        command: npx cypress run-ct --config video=false,screenshotOnRunFailure=false
    - name: Jest tests
      run: npm run test
    - name: Build nextjs
      run: npm run build
    - name: Cypress run
      uses: cypress-io/github-action@v2
      env:
        NEXTAUTH_SECRET: gitactions-test
        NEXTAUTH_URL: "http://localhost:3000"
        NODE_ENV: test
        TEST: 1
      with:
        # already installed in the previous step
        install: false
        config: video=false,screenshotOnRunFailure=false
        start: npm run dev
