name: Test Build Docker CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: (time=$(date +%s) && docker build . --file Dockerfile --tag test-build:$time && docker image rm test-build:$time)
